app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/',  ['as' => 'home', 'uses' => 'HomeController@dashboard']);

Route::get('login', 'UserSessionsController@create');
Route::post('login', 'UserSessionsController@store');
Route::get('logout', 'UserSessionsController@destroy');

Route::get('forgotten_password', 'ForgottenPasswordsController@create');
Route::post('forgotten_password', 'ForgottenPasswordsController@store');

Route::get(
    'users/change_password',
    [
        'as' => 'users.forgottenPassword',
        'uses' => 'UsersController@changePassword'
    ]
);

Route::get('pages/download/{id}', ['as' => 'pages.download', 'uses' => 'PagesController@downloadFile']);

Route::group(array('before' => 'auth'), function()
{

    Route::resource('users', 'UsersController', array('except' => 'destroy'));
    Route::get('users/{users}/change_password', ['as' => 'users.changePassword', 'uses' => 'UsersController@changePassword']);
    Route::put('users/{users}/change_password', ['as' => 'users.changePassword', 'uses' => 'UsersController@handleChangePassword']);
    Route::put('users/{users}/block', ['as' => 'users.block', 'uses' => 'UsersController@block']);
    Route::put('users/{users}/unblock', ['as' => 'users.unblock', 'uses' => 'UsersController@unblock']);

    Route::resource('securitygroups','SecurityGroupsController', array('except' => 'destroy'));
    Route::post('cases/{id}/comment', ['as' => 'cases.postComment', 'uses' => 'CasesController@postComment']);
    Route::post('pages/{type}/{id}/comment', ['as' => 'pages.postComment', 'uses' => 'PagesController@postComment']);

    Route::get('records/create/{case_id}', ['as' => 'records.create', 'uses' => 'RecordsController@create']);
    Route::post('records/create/{case_id}', ['as' => 'records.store', 'uses' => 'RecordsController@store']);
    Route::post('records/{id}/attachFile', ['as' => 'records.attachFile', 'uses' => 'RecordsController@attachFile']);
    Route::put('records/{id}/chunk_upload_finished', ['as' => 'records.chunk_upload_finished', 'uses' => 'RecordsController@chunkUploadFinished']);
    Route::get('records/download/{id}', ['as' => 'records.download', 'uses' => 'RecordsController@downloadFile']);
    Route::get('records/deleteFile/{id}', ['as' => 'records.deleteFile', 'uses' => 'RecordsController@deleteFile']);
    Route::delete('records/{id}', ['as' => 'records.destroy', 'uses' => 'RecordsController@destroy']);

    Route::resource('projects',     'ProjectsController',       array('except' => 'destroy'));
    Route::get('projects/{id}/{direction}', ['as' => 'projects.move', 'uses' => 'ProjectsController@move']);

    Route::resource('cases',        'CasesController');
    Route::resource('records',      'RecordsController',        array('except' => 'store', 'create', 'index', 'destroy'));
    Route::resource('clients',      'ClientsController',        array('except' => 'destroy'));
    Route::resource('documentation',      'DocumentationController');

    Route::post('documentation/{id}/attachFile', ['as' => 'documentation.attachFile', 'uses' => 'DocumentationController@attachFile']);
    Route::get('documentation/download/{id}', ['as' => 'documentation.download', 'uses' => 'DocumentationController@downloadFile']);
    Route::get('documentation/deleteFile/{id}', ['as' => 'documentation.deleteFile', 'uses' => 'DocumentationController@deleteFile']);
    Route::get('documentation/{id}/{direction}', ['as' => 'documentation.move', 'uses' => 'DocumentationController@move']);

    Route::get('statistics', ['as' => 'statistics.index', 'uses' => 'StatisticsController@index']);

    Route::get('pages/deleteFile/{id}', ['as' => 'pages.deleteFile', 'uses' => 'PagesController@deleteFile']);
    Route::get('pages/{type}', ['as' => 'pages.index', 'uses' => 'PagesController@index']);
    Route::get('pages/{type}/projects', ['as' => 'pages.projects', 'uses' => 'PagesController@getProjectsForPage']);
    Route::get('pages/{type}/create', ['as' => 'pages.create', 'uses' => 'PagesController@create']);
    Route::post('pages/{type}', ['as' => 'pages.store', 'uses' => 'PagesController@store']);
    Route::get('pages/{type}/{resource}', ['as' => 'pages.show', 'uses' => 'PagesController@show']);
    Route::get('pages/{type}/{resource}/edit', ['as' => 'pages.edit', 'uses' => 'PagesController@edit']);
    Route::put('pages/{type}/{resource}', ['as' => 'pages.update', 'uses' => 'PagesController@update']);
    Route::post('pages/{type}/{id}/attachFile', ['as' => 'pages.attachFile', 'uses' => 'PagesController@attachFile']);
    Route::put('pages/{type}/{id}/chunk_upload_finished', ['as' => 'pages.chunk_upload_finished', 'uses' => 'PagesController@chunkUploadFinished']);

    Route::delete('pages/{id}', ['as' => 'pages.destroy', 'uses' => 'PagesController@destroy']);

    Route::resource('search',   'SearchController',     array('only' => 'index'));

    // visible only to super admins
    Route::resource('activity', 'ActivityController', array('except' => 'destroy'));
});

Event::listen('illuminate.query', function($query, $bindings, $time, $name)
{
    $data = compact('bindings', 'time', 'name');

    // Format binding data for sql insertion
    foreach ($bindings as $i => $binding)
    {
        if ($binding instanceof \DateTime)
        {
            $bindings[$i] = $binding->format('\'Y-m-d H:i:s\'');
        }
        else if (is_string($binding))
        {
            $bindings[$i] = "'$binding'";
        }
    }

    // Insert bindings into query
    $query = str_replace(array('%', '?'), array('%%', '%s'), $query);
    $query = vsprintf($query, $bindings);

    Log::debug($query . ";");
});

/* FRONT END ROUTES */
Route::get('{clientKey}',                           array('as'=>'clientHome',    'uses'=>'ClientHomeController@index'));
Route::get('{clientKey}/article/{slug}',       array('as'=>'clientArticle', 'uses'=>'ClientHomeController@article'));
Route::get('{clientKey}/search',       array('as'=>'clientSearch', 'uses'=>'ClientHomeController@search'));
Route::get('{clientKey}/contact',       array('as'=>'clientContact', 'uses'=>'ClientHomeController@contact'));
Route::post('{clientKey}/contact',       array('as'=>'clientContact', 'uses'=>'ClientHomeController@contactSubmit'));
Route::get('{clientKey}/{type}',       array('as'=>'clientHome',    'uses'=>'ClientHomeController@index'));
Route::get('{clientKey}/{type}/{page_number}',       array('as'=>'clientHome',    'uses'=>'ClientHomeController@index'));

app/controllers/ProjectsController.php
<?php

use Policies\ProjectPolicy;
use Policies\ProjectCasePolicy;

class ProjectsController extends \BaseController {

    public function __construct()
    {
        $this->beforeFilter('csrf', array('only' => array('store', 'update')));
    }

    public function index()
    {
        $user = Auth::user();

        $get_view_preference = Input::get('view', null);

        if($get_view_preference !== null) {
            $user->view_preference = $get_view_preference;
            $user->save();
        }

        $projects = Project::where('depth', '=', 1)
            ->where('client_id', '=', $user->client_id)
            ->orderBy('lft', 'asc')
            ->get();

        return View::make(
            'Projects.index',
            array('projects' => $projects, 'user' => $user)
        );
    }

    public function create()
    {
        $user = Auth::user();
        ProjectPolicy::authorize($user, 'create');

        $project = new Project();

        if ($user->isClientAdmin() || $user->isAdmin()) {
            $userProjects = Project::where('client_id', '=', $user->client_id)->get();
        } else {
            $userProjects = ProjectPolicy::authorizedRecords($user);

            $userProjects = $userProjects->filter(function($item){
                return $item->isMainManager($user) || $item->hasManager($user);
            });
        }

        // Managers
        $managers = User::where('client_id', '=', $user->client_id)->orderBy('lastname', 'ASC')->get();

        // Security groups
        if ($user->isAdmin() || $user->isClientAdmin()) {
            $securityGroups = SecurityGroup::where('client_id', '=', $user->client_id)->orderBy('name', 'ASC')->get();
        } else {
            $securityGroups = $user->securityGroups->orderBy('name', 'ASC');
        }

        return View::make('Projects.create', array(
            'project' => $project,
            'availableParents' => $userProjects,
            'managers' => $managers,
            'securityGroups' => $securityGroups,
            'rootProject' => Project::where('name', '=', '__ROOT__PROJECT__')->where('client_id', '=', Auth::user()->client_id)->firstOrFail(),
        ));
    }

    public function store()
    {
        $data = Input::all();

        $rules = Project::$validationRules;
        $rules['project_key'] = 'required|unique:projects,project_key,NULL,id,client_id,'.Auth::user()->client_id;

        $validator = Validator::make($data, $rules);
        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator)->withInput();
        }

        ProjectPolicy::authorize(Auth::User(), 'store', NULL, $data);

        $project = new Project;

        DB::transaction(function() use ($data, &$project) {

            // Save new project
            $project->fill($data);
            $project->client_id = Auth::user()->client_id;
            $project->save();

            // Save project node position
            $parent = Project::find($data['parent_project_id']);
            $project->makeFirstChildOf($parent);

            $managers = array(new ProjectManager(array('user_id' => $data['main_manager'], 'is_main_manager' => 1)));
            if (isset($data['managers'])) {
                foreach ($data['managers'] as $manager) {
                    $managers[] = new ProjectManager(array('user_id' => $manager));
                }
            }
            $project->managers()->saveMany($managers);

            History::log([
                'action' => History::PROJECT_CREATED,
                'target_content' => $project->getFullName(),
                'ref_content' => $project->project_key,
                'target_id' => $project->id,
                'target_class' => get_class($project),
            ]);

            // Save security groups
            $project->securityGroups()->sync($data['security_groups']);

            $emailData = $project->emailRecipients()->map(function($user) use (&$project){
                return [
                    $user->email => [
                        'recipientName' => $user->getName(),
                        'name' => $user->getName(),
                        'projectName' => $project->name,
                        'link' => action(
                            'projects.show', $project->project_key
                        )
                    ]
                ];
            })->reduce(function($result, $item){
                return array_merge($result, $item);
            }, []);

            $emailData['subject'] = 'New Project - ' . $project->name;

            MandrillEmailSender::send(
                'project-created',
                $emailData
            );

        });

        return Redirect::route(
            'projects.show', array('project_key' => $project->project_key)
        );
    }

    public function update($project_key)
    {
        $project = Project::where('project_key', '=', $project_key)
            ->where('client_id', '=', Auth::user()->client_id)
            ->firstOrFail();

        $data = Input::all();

        $rules = Project::$validationRules;
        $rules['project_key'] = 'required|unique:projects,project_key,'.$project->id.',id,client_id,'.Auth::user()->client_id;

        $validator = Validator::make($data, $rules);

        ProjectPolicy::authorize(Auth::User(), 'update', $project, $data);

        $parentProjectId = $data['parent_project_id'];
        $forbiddenIds = $project->getDescendantsAndSelf()->lists('id');

        if($parentProjectId && in_array($parentProjectId, $forbiddenIds)){
            $validator->getMessageBag()->add('parent_project_id', 'Wrong parent node');
        }

        if (!$validator->messages()->isEmpty()) {
            return Redirect::back()->withErrors($validator)->withInput();
        }

        DB::transaction(function() use ($data, &$project) {

            // Update managers
            $project->managers()->delete();
            $managers = array(
                new ProjectManager(array('user_id' => $data['main_manager'], 'is_main_manager' => 1))
            );
            if (isset($data['managers'])) {
                foreach ($data['managers'] as $manager) {
                    $managers[] = new ProjectManager(array('user_id' => $manager));
                }
            }
            $project->managers()->saveMany($managers);

            // Update project parent or make it root
            $parent = $project->parent_project_id;
            if ($data['parent_project_id'] != $parent && $data['parent_project_id'] != $project->id) {
                $parent = Project::find($data['parent_project_id']);
                $project->makeFirstChildOf($parent);
            }

            $data['enable_cases'] = isset($data['enable_cases']);
            $data['enable_wiki'] = isset($data['enable_wiki']);
            $data['enable_pages'] = isset($data['enable_pages']);
            $data['enable_forms'] = isset($data['enable_forms']);

            // Update security groups
            $project->securityGroups()->sync($data['security_groups']);

            $project->update($data);

            History::log([
                'action' => History::PROJECT_UPDATED,
                'target_content' => $project->getFullName(),
                'ref_content' => $project->project_key,
                'target_id' => $project->id,
                'target_class' => get_class($project),
            ]);

            $emailData = $project->emailRecipients()->map(function($user) use (&$project){
                return [
                    $user->email => [
                        'recipientName' => $user->getName(),
                        'projectName' => $project->name,
                        'name' => $user->getName(),
                        'link' => action(
                            'projects.show', $project->project_key
                        )
                    ]
                ];
            })->reduce(function($result, $item){
                return array_merge($result, $item);
            }, []);

            $emailData['subject'] = 'Project Update - ' . $project->name;

            MandrillEmailSender::send(
                'project-updated',
                $emailData
            );
        });

        return Redirect::route(
            'projects.show', array('project_key' => $project->project_key)
        );
    }

    public function show($project_key)
    {
        $project = Project::where('project_key', '=', $project_key)
            ->where('client_id', '=', Auth::User()->client_id)
            ->firstOrFail();

        $user = Auth::user();

        ProjectPolicy::authorize($user, 'show', $project);

        $subprojects = $project->getDescendants();

        $projects = $user->projectsQueryBuilder()->get();

        $cases = ProjectCasePolicy::authorizedRecordsBuilder(
            $user
        )
            ->whereIn('project_id', [$project->id] + $subprojects->lists('id'))
            ->with('project', 'assignedTo', 'projectCaseStatus')
            ->orderBy('cases.created_at', 'desc')
            ->take(10)
            ->get();

        if ($cases->count()) {
            $comments = ProjectCaseComment::whereIn(
                'project_case_id', $cases->lists('id')
            )
                ->with('user', 'projectCase', 'projectCase.project')
                ->orderBy('updated_at', 'DESC')
                ->take(10)
                ->get();
        } else {
            $comments = new \Illuminate\Database\Eloquent\Collection();
        }

        $pages = Page::whereIn('project_id', [$project->id] + $subprojects->lists('id'))
            ->where('depth', '>', 0)
            ->with('project')
            ->orderBy('created_at', 'DESC')
            ->take(10);

        if ($user->isNormalUser()) {
            $pages->where('is_public', '=', false);
        }
        $pages = $pages->get();

        return View::make('Projects.show', array(
            'project' => $project,

app/views/Projects/create.blade.php
@extends('layouts.client')

@section('content')

@include('Projects/crumbs')

	<div class="row">
	  <div class="col-md-9 col-sm-7">
	    <h2>Create a New Project</h2>
	  </div>
	</div>

	@include('Projects/form')

@endsection

app/views/Projects/crumbs.blade.php
<ol class="breadcrumb bc-3">
    <li>
        <a href="/"><i class="entypo-home"></i>Home</a>
    </li>
    <li>
        <a href="{{ route('projects.index') }}">Projects</a>
    </li>
    @if (isset($project))

        @if (is_null($project->id))

            <li>
                <a href="{{ URL::route('projects.create') }}">Create new project</a>
            </li>

        @else
            @foreach ($project->getAncestors() as $key => $parent)
              @if ($parent->depth > 0)
                <li><a href="{{ URL::route('projects.show', $parent->project_key) }}">{{ $parent->name }} ({{ $parent->project_key }})</a></li>
              @endif
            @endforeach

            <li>
                <a href="{{ URL::route('projects.show', $project->project_key) }}">{{ $project->name }} ({{ $project->project_key }})</a>
            </li>
        @endif

    @endif

</ol>

app/views/Projects/edit.blade.php
@extends('layouts.client')

@section('content')
@include('Projects/crumbs')

<h1>{{ $project->name }} ({{$project->project_key}})</h1>
<p>
	@if ($project->enable_cases)<div class="label label-info">Cases</div>@endif
	@if ($project->enable_wiki)<div class="label label-info">Wiki</div>@endif
	@if ($project->enable_pages)<div class="label label-info">Pages</div>@endif
	@if ($project->enable_forms)<div class="label label-info">Forms</div>@endif
</p>


@include('Projects/form')

@endsection

app/views/Projects/errors.blade.php
<div class="row">
  <div class="col-md-12">
  	<div class="alert alert-danger">
  	<h4>Please fix following errors:</h4>
  	<ul>
    @foreach ($errors->all() as $err)
    	<li>{{ $err }}</li>
	@endforeach
	</ul>
	</div>
  </div>
</div>

<hr>

app/views/Projects/form.blade.php
@include('includes/admin/errors')

@if (isset($project) && !is_null($project->project_key))
    {{ Form::model($project, array('route' => array('projects.update', $project->project_key), 'class'=>'form-horizontal form-groups-bordered', 'method' => 'put', 'role' => 'form')) }}
@else
    {{ Form::open(array('route' => 'projects.store', 'class'=>'form-horizontal form-groups-bordered', 'role' => 'form')) }}
@endif


<br>

<div class="row">
    <div class="col-sm-2">
        {{ Form::label('project_key', 'Project key:') }}<br>
        {{ Form::text('project_key', $project->project_key, array('placeholder' => 'Project Key', 'class' => 'form-control input-lg')) }}
    </div>
    <div class="col-sm-6">
        {{ Form::label('name', 'Title:') }}<br>
        {{ Form::text('name', $project->name, array('placeholder' => 'Project Name', 'class' => 'form-control input-lg')) }}
    </div>
    <div class="col-sm-4">
        <?php
            $parentsTree = array();
            foreach ($availableParents as $parent) {
              if ($parent->depth === 1) {
                $parentsTree[$parent->id] = $parent->project_key . ' - ' . $parent->name;
                foreach ($parent->getDescendants() as $sub) {
                  $parentsTree[$sub->id] = str_repeat('--', $sub->depth-1) . ' ' . $sub->project_key . ' - ' . $sub->name;
                }
              }
            }
          ?>
        {{ Form::label('parent_project_id', 'Parent Project:') }}<br>
        {{ Form::select('parent_project_id', [$rootProject->id => 'None'] + $parentsTree, $project->parent_project_id, array('class' => 'form-control input-lg')) }}
    </div>
</div>
<br>

<div class="row">
    <div class="col-sm-4">
        {{ Form::label('main_manager', 'Manager:') }}<br>
        <select name="main_manager" id="main_manager" class="form-control input-lg">
            @foreach ($managers as $key => $manager)
                <option value="{{ $manager->id }}" @if ($project->isMainManager($manager)) selected="selected" @endif>{{ $manager->name }} ({{ $manager->job_title }})</option>
            @endforeach
        </select>
    </div>
    <div class="col-sm-4">
        {{ Form::label('managers', 'Manager Representative(s):') }}<br>
        <select multiple="multiple" name="managers[]" id="managers" class="form-control input-lg">
            @foreach ($managers as $key => $manager)
                <option value="{{ $manager->id }}" @if ($project->hasManager($manager)) selected="selected" @endif>{{ $manager->name }} ({{ $manager->job_title }})</option>
            @endforeach
        </select>
    </div>
    <div class="col-sm-4">
        {{ Form::label('security_groups', 'Security Group(s):') }}<br>
        <select multiple="multiple" name="security_groups[]" id="security_groups" class="form-control input-lg">
            @foreach ($securityGroups as $group)
                <option value="{{ $group->id }}" @if ($project->isInSecurityGroup($group)) selected="selected" @endif>{{ $group->name }}</option>
            @endforeach
        </select>
    </div>
</div>
<br>
<div class="row">
    <div class="col-sm-8">
        {{ Form::label('summary', 'Description:') }}<br>
        {{ Form::textarea('summary', $project->summary, array('placeholder' => 'Description', 'class' => 'form-control wysihtml5', 'data-stylesheet-url' => 'assets/css/wysihtml5-color.css', 'rows' => 9)) }}

        <br><br>
    </div>

    <div class="col-sm-4">
        <strong>Extras:</strong>
        <div class="checkbox checkbox-primary">
            {{ Form::checkbox('enable_cases', 1, $project->enable_cases || true, array('id' => 'enable_cases')) }}
            <label for="enable_cases">Enable Cases</label>
        </div>

        @if(Auth::User()->client->enable_wiki)
        <div class="checkbox checkbox-primary">
            {{ Form::checkbox('enable_wiki', 1, $project->enable_wiki || true, array('id' => 'enable_wiki')) }}
            <label for="enable_wiki">Enable Wiki</label>
        </div>
        @endif

        @if(Auth::User()->client->enable_intranet)
        <div class="checkbox checkbox-primary">
            {{ Form::checkbox('enable_pages', 1, $project->enable_pages || true, array('id' => 'enable_pages')) }}
            <label for="enable_pages">Enable Pages</label>
        </div>
        @endif

        @if(Auth::User()->client->enable_forms)
        <div class="checkbox checkbox-primary">
            {{ Form::checkbox('enable_forms', 1, $project->enable_forms || true, array('id' => 'enable_forms')) }}
            <label for="enable_forms">Enable Forms</label>
        </div>
        @endif

        <br><br>
        {{ Form::label('theme_color', 'Project Color:') }}<br>
        {{ Form::text('theme_color', $project->theme_color, array('placeholder' => 'Project Color', 'id' => 'theme_color', 'class' => 'form-control input-lg')) }}
    </div>

</div>
<div class="row">
    <div class="col-md-8">
        <button type="submit" class="btn btn-success pull-right">
            @if ($project->id) Update Project @else Create Project @endif
        </button>
    </div>
</div>

<br /><br />



{{ Form::close() }}

<script type="text/javascript">
    $(document).ready(function() {
        $("#security_groups").select2();
        $("#managers").select2();
        $('#theme_color').colorpicker();
    });
</script>

app/views/Projects/grid.blade.php
@if ($projects->count())
    @foreach ($projects as $project)
        @include('Projects/grid-item', array('projects' => $projects))
    @endforeach

    <script type="text/javascript">
    $(function(){
        $('project').click(function(event){

            if($(event.target).closest(".btn-group").length) return;
            if ($(this).data('access') == 1) {
                location.href = $(this).attr("rel");
            }
        });
    });
    </script>
@endif

app/views/Projects/index.blade.php
@extends('layouts.client')

@section('content')

@include('Projects/crumbs')

<div class="row k1-heading-row">
    <div class="col-md-7 col-sm-6 col-xs-5"><h1>Projects</h1></div>
    <div class="col-md-5 col-sm-6 col-xs-7">
        <div class="pull-right">
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <i {{{ ($user->view_preference == 0 ? 'class=entypo-list' : 'class=entypo-layout') }}} ></i> View <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li {{{ ($user->view_preference == 0 ? 'class=active' : '') }}}>
                        <a href="{{ route('projects.index', array('view'=>'0')) }}"><i class="entypo-list"></i> List</a>
                    </li>
                    <li {{{ ($user->view_preference == 1 ? 'class=active' : '') }}}>
                        <a href="{{ route('projects.index', array('view'=>'1')) }}"><i class="entypo-layout"></i> Grid</a>
                    </li>
                </ul>
            </div>

            @if (Auth::user()->isClientAdmin() || Auth::user()->isAdmin())
                <a href={{ URL::route('projects.create') }} class="btn btn-primary">
                    <i class="entypo-plus"></i>
                    Create a New Project
                </a>
            @endif
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @if ($user->view_preference == 0)
            @include('Projects/list', array('projects' => $projects))
        @else
            @include('Projects/grid', array('projects' => $projects))
        @endif
    </div>
</div>

@endsection

app/views/Projects/show.blade.php
@extends('layouts.client')

@section('content')
@include('Projects/crumbs')

<div class="row k1-heading-row">
    <div class="col-md-7 col-sm-6 col-xs-12">
        <h1>
            {{ $project->name }} ({{$project->project_key}})
        </h1>
        
            @if ($project->enable_cases)<div class="label label-info">Cases</div>@endif
            @if ($project->enable_wiki)<div class="label label-info">Wiki</div>@endif
            @if ($project->enable_pages)<div class="label label-info">Intranet</div>@endif
            @if ($project->enable_forms)<div class="label label-info">Forms</div>@endif
        
    </div>

    @if ($canEdit)
    <div class="col-md-5 col-sm-6 col-xs-12 actionbar">
        <a href="{{ route('projects.edit', array('project_key' => $project->project_key)) }}" class="btn  btn-primary">
            <i class="entypo-pencil"></i>Edit Project</a>

        @if ($canCreateCase)
        &nbsp; <a href={{ URL::route('cases.create') }} class="btn btn-success pull-right">
            <i class="entypo-plus"></i>
            Create a New Case
        </a>
        @endif
    </div>
    @endif

</div>

<div class="row">
    <div class="col-md-8">
        <h2>Summary</h2>
        <p>
            {{ $project->summary }}
        </p>
    </div>
    <div class="col-md-3">
        <h2>Project Details</h2>
        <p>
            <strong>Project Key:</strong> {{ $project->project_key }}<br>
            <strong>Manager:</strong>
                @foreach ($project->managers as $manager)
                    @if ($manager->is_main_manager) {{$manager->user->getName()}} @endif
                @endforeach
            <br>
            <strong>Manager Representative(s):</strong><br />
                @foreach ($project->managers as $manager)
                    @if (!$manager->is_main_manager) {{$manager->user->getName()}}<br /> @endif
                @endforeach

            <strong>Security Group(s): </strong>
            <?php $grps = []; ?>
            @foreach ($project->securityGroups as $group)
                <?php $grps[] = $group->name; ?>
            @endforeach
            <?php echo implode(', ', $grps); ?>
            <br>

            <strong>Created:</strong> {{ Dates::localizeDateTime($project->created_at)->format('d M Y') }}<br>
            <strong>Updated:</strong> {{ Dates::showTimeAgo($project->updated_at) }}<br>
        </p>
    </div>
</div>

@include('Projects/show/subprojects')

<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <li role="presentation"><a href="#cases">Cases</a></li>
            <li role="presentation"><a href="#comments">Latest Comments</a></li>
            @if ($pages->count()) <li role="presentation"><a href="#pages">Intranet</a></li> @endif
            <li role="presentation"><a href="#history">History</a></li>
        </ul>
    </div>
</div>


<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane" id="cases">
        @include('Projects/show/cases', array('project' => $project))
    </div>

    <div role="tabpanel" class="tab-pane" id="comments">
        @include('Projects/show/comments')
    </div>

    <div role="tabpanel" class="tab-pane" id="pages">
        @include('Projects/show/pages')
    </div>

    <div role="tabpanel" class="tab-pane" id="history">
        @include('includes/admin/history')
    </div>
</div>

<script type="text/javascript">
    var bindClickListener = function (object) {
        object.click(function (e) {
            e.preventDefault()
            object.tab('show')
        });
    }

    $(function() {
        $('.nav.nav-tabs').find('a').each(function(){
            bindClickListener($(this));
        });

        $('.nav.nav-tabs li:first a').tab('show');
    });
</script>
@endsection