app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/',  ['as' => 'home', 'uses' => 'HomeController@dashboard']);

Route::get('login', 'UserSessionsController@create');
Route::post('login', 'UserSessionsController@store');
Route::get('logout', 'UserSessionsController@destroy');

Route::get('forgotten_password', 'ForgottenPasswordsController@create');
Route::post('forgotten_password', 'ForgottenPasswordsController@store');

Route::get(
    'users/change_password',
    [
        'as' => 'users.forgottenPassword',
        'uses' => 'UsersController@changePassword'
    ]
);

Route::get('pages/download/{id}', ['as' => 'pages.download', 'uses' => 'PagesController@downloadFile']);

Route::group(array('before' => 'auth'), function()
{

    Route::resource('users', 'UsersController', array('except' => 'destroy'));
    Route::get('users/{users}/change_password', ['as' => 'users.changePassword', 'uses' => 'UsersController@changePassword']);
    Route::put('users/{users}/change_password', ['as' => 'users.changePassword', 'uses' => 'UsersController@handleChangePassword']);
    Route::put('users/{users}/block', ['as' => 'users.block', 'uses' => 'UsersController@block']);
    Route::put('users/{users}/unblock', ['as' => 'users.unblock', 'uses' => 'UsersController@unblock']);

    Route::resource('securitygroups','SecurityGroupsController', array('except' => 'destroy'));
    Route::post('cases/{id}/comment', ['as' => 'cases.postComment', 'uses' => 'CasesController@postComment']);
    Route::post('pages/{type}/{id}/comment', ['as' => 'pages.postComment', 'uses' => 'PagesController@postComment']);

    Route::get('records/create/{case_id}', ['as' => 'records.create', 'uses' => 'RecordsController@create']);
    Route::post('records/create/{case_id}', ['as' => 'records.store', 'uses' => 'RecordsController@store']);
    Route::post('records/{id}/attachFile', ['as' => 'records.attachFile', 'uses' => 'RecordsController@attachFile']);
    Route::put('records/{id}/chunk_upload_finished', ['as' => 'records.chunk_upload_finished', 'uses' => 'RecordsController@chunkUploadFinished']);
    Route::get('records/download/{id}', ['as' => 'records.download', 'uses' => 'RecordsController@downloadFile']);
    Route::get('records/deleteFile/{id}', ['as' => 'records.deleteFile', 'uses' => 'RecordsController@deleteFile']);
    Route::delete('records/{id}', ['as' => 'records.destroy', 'uses' => 'RecordsController@destroy']);

    Route::resource('projects',     'ProjectsController',       array('except' => 'destroy'));
    Route::get('projects/{id}/{direction}', ['as' => 'projects.move', 'uses' => 'ProjectsController@move']);

    Route::resource('cases',        'CasesController');
    Route::resource('records',      'RecordsController',        array('except' => 'store', 'create', 'index', 'destroy'));
    Route::resource('clients',      'ClientsController',        array('except' => 'destroy'));
    Route::resource('documentation',      'DocumentationController');

    Route::post('documentation/{id}/attachFile', ['as' => 'documentation.attachFile', 'uses' => 'DocumentationController@attachFile']);
    Route::get('documentation/download/{id}', ['as' => 'documentation.download', 'uses' => 'DocumentationController@downloadFile']);
    Route::get('documentation/deleteFile/{id}', ['as' => 'documentation.deleteFile', 'uses' => 'DocumentationController@deleteFile']);
    Route::get('documentation/{id}/{direction}', ['as' => 'documentation.move', 'uses' => 'DocumentationController@move']);

    Route::get('statistics', ['as' => 'statistics.index', 'uses' => 'StatisticsController@index']);

    Route::get('pages/deleteFile/{id}', ['as' => 'pages.deleteFile', 'uses' => 'PagesController@deleteFile']);
    Route::get('pages/{type}', ['as' => 'pages.index', 'uses' => 'PagesController@index']);
    Route::get('pages/{type}/projects', ['as' => 'pages.projects', 'uses' => 'PagesController@getProjectsForPage']);
    Route::get('pages/{type}/create', ['as' => 'pages.create', 'uses' => 'PagesController@create']);
    Route::post('pages/{type}', ['as' => 'pages.store', 'uses' => 'PagesController@store']);
    Route::get('pages/{type}/{resource}', ['as' => 'pages.show', 'uses' => 'PagesController@show']);
    Route::get('pages/{type}/{resource}/edit', ['as' => 'pages.edit', 'uses' => 'PagesController@edit']);
    Route::put('pages/{type}/{resource}', ['as' => 'pages.update', 'uses' => 'PagesController@update']);
    Route::post('pages/{type}/{id}/attachFile', ['as' => 'pages.attachFile', 'uses' => 'PagesController@attachFile']);
    Route::put('pages/{type}/{id}/chunk_upload_finished', ['as' => 'pages.chunk_upload_finished', 'uses' => 'PagesController@chunkUploadFinished']);

    Route::delete('pages/{id}', ['as' => 'pages.destroy', 'uses' => 'PagesController@destroy']);

    Route::resource('search',   'SearchController',     array('only' => 'index'));

    // visible only to super admins
    Route::resource('activity', 'ActivityController', array('except' => 'destroy'));
});

Event::listen('illuminate.query', function($query, $bindings, $time, $name)
{
    $data = compact('bindings', 'time', 'name');

    // Format binding data for sql insertion
    foreach ($bindings as $i => $binding)
    {
        if ($binding instanceof \DateTime)
        {
            $bindings[$i] = $binding->format('\'Y-m-d H:i:s\'');
        }
        else if (is_string($binding))
        {
            $bindings[$i] = "'$binding'";
        }
    }

    // Insert bindings into query
    $query = str_replace(array('%', '?'), array('%%', '%s'), $query);
    $query = vsprintf($query, $bindings);

    Log::debug($query . ";");
});

/* FRONT END ROUTES */
Route::get('{clientKey}',                           array('as'=>'clientHome',    'uses'=>'ClientHomeController@index'));
Route::get('{clientKey}/article/{slug}',       array('as'=>'clientArticle', 'uses'=>'ClientHomeController@article'));
Route::get('{clientKey}/search',       array('as'=>'clientSearch', 'uses'=>'ClientHomeController@search'));
Route::get('{clientKey}/contact',       array('as'=>'clientContact', 'uses'=>'ClientHomeController@contact'));
Route::post('{clientKey}/contact',       array('as'=>'clientContact', 'uses'=>'ClientHomeController@contactSubmit'));
Route::get('{clientKey}/{type}',       array('as'=>'clientHome',    'uses'=>'ClientHomeController@index'));
Route::get('{clientKey}/{type}/{page_number}',       array('as'=>'clientHome',    'uses'=>'ClientHomeController@index'));

app/views/includes/admin/activity-action.blade.php
@if ($activity->action === History::PROJECT_CREATED)
    created new project <a href="{{ action('projects.show', $activity->ref_content) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::PROJECT_UPDATED)
    updated project <a href="{{ action('projects.show', $activity->ref_content) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::CASE_CREATED)
    created new case <a href="{{ action('cases.show', $activity->target_id) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::CASE_UPDATED)
    updated case <a href="{{ action('cases.show', $activity->target_id) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::CASE_CLOSED)
    closed case <a href="{{ action('cases.show', $activity->target_id) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::CASE_COMMENTED)
    added comment to case <a href="{{ action('cases.show', $activity->ref_id) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::PAGE_CREATED)
    <?php $pageType = Page::$pageTypeNames[$activity->additional_data]; ?>
    created new {{ $pageType }} page <a href="{{ action('pages.show', ['type' => $pageType, 'id' => $activity->target_id]) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::PAGE_UPDATED)
    <?php $pageType = Page::$pageTypeNames[$activity->additional_data]; ?>
    updated {{ $pageType }} page <a href="{{ action('pages.show', ['type' => $pageType, 'id' => $activity->target_id]) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::PAGE_FILE_UPLOADED)
    <?php $pageType = Page::$pageTypeNames[$activity->additional_data]; ?>
    uploaded new attachment for {{ $pageType }} page <a href="{{ action('pages.show', ['type' => $pageType, 'id' => $activity->ref_id]) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::PAGE_FILE_DOWNLOADED)
    <?php $pageType = Page::$pageTypeNames[$activity->additional_data]; ?>
    downloaded attachment in {{ $pageType }} page <a href="{{ action('pages.show', ['type' => $pageType, 'id' => $activity->ref_id]) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::PAGE_FILE_DELETED)
    <?php $pageType = Page::$pageTypeNames[$activity->additional_data]; ?>
    deleted attachment in {{ $pageType }} page <a href="{{ action('pages.show', ['type' => $pageType, 'id' => $activity->ref_id]) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::PAGE_COMMENTED)
    <?php $pageType = Page::$pageTypeNames[$activity->additional_data]; ?>
    added comment to page <a href="{{ action('pages.show', ['type' => $pageType, 'id' => $activity->target_id]) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::RECORD_CREATED)
    created new record <a href="{{ action('records.show', $activity->target_id) }}">{{ $activity->target_content }}</a> in Case <a href="{{ action('cases.show', $activity->ref_id) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::RECORD_UPDATED)
    updated record <a href="{{ action('records.show', $activity->target_id) }}">{{ $activity->target_content }}</a> in Case <a href="{{ action('cases.show', $activity->ref_id) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::RECORD_FILE_UPLOADED)
    uploaded new attachment for record <a href="{{ action('records.show', $activity->ref_id) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::RECORD_FILE_DOWNLOADED)
    downloaded an attachment in record <a href="{{ action('records.show', $activity->ref_id) }}">{{ $activity->ref_content }}</a>
@elseif ($activity->action === History::RECORD_FILE_DELETED)
    deleted an attachment in record <a href="{{ action('records.show', $activity->target_id) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::USER_CREATED)
    created new user <a href="#">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::USER_UPDATED)
    updated user <a href="#">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::USER_BLOCKED)
    blocked <a href="#">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::USER_UNBLOCKED)
    unblocked <a href="#">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::USER_PASSWORD_CHANGED)
    changed his password
@elseif ($activity->action === History::USER_PASSWORD_RESET_INIT)
    initialized password reset
@elseif ($activity->action === History::SECURITY_GROUP_CREATED)
    created new security group <a href="{{ action('SecurityGroupsController@show', $activity->target_id) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::SECURITY_GROUP_UPDATED)
    updated security group <a href="{{ action('SecurityGroupsController@show', $activity->target_id) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::SECURITY_GROUP_USER_ADDED)
    added <a href="#">{{ $activity->ref_content}}</a> to <a href="{{ action('SecurityGroupsController@show', $activity->target_id) }}">{{ $activity->target_content }}</a>
@elseif ($activity->action === History::SECURITY_GROUP_USER_REMOVED)
    removed <a href="#">{{ $activity->ref_content }}</a> from <a href="{{ action('SecurityGroupsController@show', $activity->target_id) }}">{{ $activity->target_content }}</a>
@else
    {{ History::$actionMapping[$activity->action] }}
@endif

app/views/includes/admin/activity-feed.blade.php
<section class="activity-feed">
    @if ($latestActivities->count())
        @foreach ($latestActivities as $activity)

                {{-- PAGES --}}
                @if ($activity->action == History::PAGE_CREATED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'star-empty',
                        'text'=>'created page',
                        'link'=> link_to_route('pages.show', $activity->target_content, ['id' => $activity->target_id, 'type' => Page::$pageTypeNames[$activity->additional_data]])
                    ))

                @elseif ($activity->action == History::PAGE_UPDATED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'pencil',
                        'text'=>'updated page',
                        'link'=> link_to_route('pages.show', $activity->target_id, ['id' => $activity->target_id, 'type' => Page::$pageTypeNames[$activity->additional_data]])
                    ))

                @elseif ($activity->action == History::PAGE_CHUNK_UPLOAD_FINISHED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'attach',
                        'text'=>'uploaded new files to',
                        'link'=> link_to_route('pages.show', $activity->ref_content, ['id' => $activity->target_id, 'type' => Page::$pageTypeNames[$activity->additional_data]])
                    ))

                @elseif ($activity->action == History::PAGE_FILE_DELETED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'cancel',
                        'text'=>'deleted an attachment from',
                        'link'=> link_to_route('pages.show', $activity->ref_content, ['id' => $activity->target_id, 'type' => Page::$pageTypeNames[$activity->additional_data]]),
                    ))

                @elseif ($activity->action == History::PAGE_COMMENTED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'chat',
                        'text'=>'posted a comment in',
                        'link'=> link_to_route('pages.show', $activity->ref_content, ['id' => $activity->ref_content])
                    ))

                {{-- RECORDS --}}
                @elseif ($activity->action == History::RECORD_CREATED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'star-empty',
                        'text'=>'created record',
                        'link'=> link_to_route('records.show', $activity->target_content, ['id' => $activity->target_id]),
                        'link2' => link_to_route('cases.show', $activity->ref_content, ['id' => $activity->ref_id])
                    ))

                @elseif ($activity->action == History::RECORD_UPDATED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'pencil',
                        'text'=>'updated record',
                        'link'=> link_to_route('records.show', $activity->target_content, ['id' => $activity->target_id]),
                        'link2' => link_to_route('cases.show', $activity->ref_content, ['id' => $activity->ref_id])
                    ))

                @elseif ($activity->action == History::RECORD_CHUNK_UPLOAD_FINISHED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'attach',
                        'text'=>'uploaded new files to',
                        'link'=> link_to_route('records.show', $activity->target_content, ['id' => $activity->target_id]),
                        'link2' => link_to_route('cases.show', $activity->ref_content, ['id' => $activity->ref_id])
                    ))

                @elseif ($activity->action == History::RECORD_FILE_DELETED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'cancel',
                        'text'=>'deleted file in',
                        'link'=> link_to_route('records.show', $activity->target_content, ['id' => $activity->target_id]),
                        'link2' => link_to_route('cases.show', $activity->ref_content, ['id' => $activity->ref_id])
                    ))

                @elseif ($activity->action == History::RECORD_DELETED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'cancel',
                        'text'=>'deleted record '.$activity->ref_content.' in',
                        'link'=> link_to_route('cases.show', $activity->target_content, ['id' => $activity->target_id])
                    ))

                {{-- CASES --}}
                @elseif ($activity->action == History::CASE_CREATED)
                   @include ('Activity/feed-item', array(
                        'icon'=>'star-empty',
                        'text'=> 'created case',
                        'link'=> link_to_route('cases.show', $activity->target_content, ['id' => $activity->target_id])
                    ))

                @elseif ($activity->action == History::CASE_UPDATED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'pencil',
                        'text'=>'updated case',
                        'link'=> link_to_route('cases.show', $activity->target_content, ['id' => $activity->target_id])
                    ))

                @elseif ($activity->action == History::CASE_COMMENTED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'chat',
                        'text'=>'posted a comment in',
                        'link'=> link_to_route('cases.show', $activity->ref_content, ['id' => $activity->ref_id])
                    ))

                @elseif ($activity->action == History::CASE_CLOSED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'lock',
                        'text'=> 'closed case',
                        'link'=> link_to_route('cases.show', $activity->target_content, ['id' => $activity->target_id])
                    ))

                @elseif ($activity->action == History::CASE_DELETED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'cancel',
                        'text'=> 'deleted case '.$activity->ref_id.' '.$activity->ref_content
                    ))

                {{-- PROJECTS --}}
                @elseif ($activity->action == History::PROJECT_CREATED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'star-empty',
                        'text'=>'created project',
                        'link'=> link_to_route('projects.show', $activity->target_content, ['id' => $activity->ref_content])
                    ))

                @elseif ($activity->action == History::PROJECT_UPDATED)
                    @include ('Activity/feed-item', array(
                        'icon'=>'pencil', 'text'=>'updated project',
                        'link'=> link_to_route('projects.show', $activity->target_content, ['id' => $activity->ref_content])
                    ))

                @else
                    @include ('Activity/feed-item', array(
                        'icon'=>'info',
                        'text'=> History::$actionMapping[$activity->action]
                    ))


                {{-- commenting out for now
                   @elseif ($activity->action == History::USER_PASSWORD_CHANGED)
                      changed the password of {{ link_to_route('users.show', $activity->target_id, ['id' => $activity->target_id]) }}
                   @elseif ($activity->action == History::USER_BLOCKED)
                      blocked user {{ link_to_route('users.show', $activity->target_content, ['id' => $activity->target_id]) }}
                   @elseif ($activity->action == History::USER_UNBLOCKED)
                      unblocked user {{ link_to_route('users.show', $activity->target_content, ['id' => $activity->target_id]) }}
                   @elseif ($activity->action == History::USER_UPDATED)
                      updated user {{ link_to_route('users.show', $activity->target_content, ['id' => $activity->target_id]) }}
                --}}


                @endif
       @endforeach
    @else
       <h3>User has no activities yet.</h3>
    @endif
</section>

app/views/includes/admin/activity-user-thumb.blade.php
<aside class="user-avatar">
    <a href="{{ route('users.show', $user->id) }}">
        <img src="{{ $user->getAvatarLink('/assets/admin/images/member.jpg') }}" alt="" class="img-circle" width="32" height="32">
    </a>
</aside>

app/views/includes/admin/errors.blade.php
@if ($errors->count())
<div class="row">
  <div class="col-md-12">
  	<div class="alert alert-danger">
  	<h4>Please fix following errors:</h4>
  	<ul>
    @foreach ($errors->all() as $err)
    	<li>{{ $err }}</li>
	@endforeach
	</ul>
	</div>
  </div>
</div>

<hr>
@endif

app/views/includes/admin/foot.blade.php
<link rel="stylesheet" href="/assets/admin/js/jvectormap/jquery-jvectormap-1.2.2.css">
<link rel="stylesheet" href="/assets/admin/js/rickshaw/rickshaw.min.css">
<link rel="stylesheet" href="/assets/admin/js/wysihtml5/bootstrap-wysihtml5.css">
<link rel="stylesheet" href="/assets/admin/js/selectboxit/jquery.selectBoxIt.css">
<link rel="stylesheet" href="/assets/admin/js/vertical-timeline/css/component.css">
<link rel="stylesheet" href="/assets/admin/js/dropzone/basic.css">
<link rel="stylesheet" href="/assets/admin/js/dropzone/dropzone.css">

<!-- Bottom Scripts -->

<script src="/assets/admin/js/bootstrap.js"></script>

<script src="/assets/admin/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/admin/js/wysihtml5/bootstrap-wysihtml5.js"></script>
<script src="/assets/admin/js/jquery.wysihtml5_size_matters.js"></script>

<script src="/assets/admin/js/k1-custom.js"></script>

<script src="/assets/admin/js/jquery.peity.min.js"></script>

<link rel="stylesheet" href="/assets/admin/js/datatables/responsive/css/datatables.responsive.css">
<link rel="stylesheet" href="/assets/admin/js/select2/select2-bootstrap.css">
<link rel="stylesheet" href="/assets/admin/js/select2/select2.css">

<!-- Bottom Scripts -->
<script src="/assets/admin/js/jquery.dataTables.min.js"></script>
<script src="/assets/admin/js/datatables/TableTools.min.js"></script>
<script src="/assets/admin/js/dataTables.bootstrap.js"></script>
<script src="/assets/admin/js/datatables/jquery.dataTables.columnFilter.js"></script>
<script src="/assets/admin/js/datatables/lodash.min.js"></script>
<script src="/assets/admin/js/datatables/responsive/js/datatables.responsive.js"></script>
<script src="/assets/admin/js/select2/select2.min.js"></script>

<script src="/assets/admin/js/fileinput.js"></script>
<script src="/assets/admin/js/dropzone/dropzone.js"></script>



@include('includes.shared.analytics')

app/views/includes/admin/header.blade.php
 <header class="k1-page-header">
    <a href="/" class="logo">
        <img src="/assets/admin/images/k1cms_logo_small.png" alt="K1 CMS" />
    </a>

    <nav class="headerNav">
        @include('includes/admin/headerNav')
    </nav>

    <nav class="mobileNav">
        @include('includes/admin/mobileNav')
    </nav>
</header>

app/views/includes/admin/headerNav.blade.php
<ul>
    <li>
        <form action="{{ action('search.index') }}" method="GET">
            <i class="entypo-search"></i>
            <input type="text" name="q" class="header-search" value="{{ isset($query) ? $query : '' }}" placeholder="Search" />
        </form>
    </li>

    <li class="dropdown">
        <a href="#"  data-toggle="dropdown">
            <i class="entypo-help-circled"></i><span class="caret"></span>
        </a>

        <ul class="dropdown-menu">
            @include('includes/admin/nav/support')
        </ul>
    </li>

    <li style="display:none">
        <a href="{{ route('documentation.index') }}">
            <i class="entypo-info-circled"></i>
        </a>
    </li>

    <li class="profile-info dropdown">

        <a href="#" class="dropdown-toggle" style="margin-right: 30px;" data-toggle="dropdown">
            <span style="margin-right: 30px;">{{Auth::user()->getName()}}
                <span class="caret"></span>
            </span>
            <img src="{{Auth::user()->getAvatarLink('/assets/admin/images/member.jpg')}}" alt="" class="avatar" width="44" height="44" />
        </a>

        <ul class="dropdown-menu">
            @include('includes/admin/nav/profile')
        </ul>
    </li>
</ul>

app/views/includes/admin/mainNav.blade.php
<ul>
    <li {{{ (Request::is('/') ? 'class=active' : '') }}}>
        <a href="/">
            <i class="entypo-gauge"></i><span>Dashboard</span>
        </a>
    </li>
    @if (Auth::user()->isAdmin())
    <li {{{ (Request::is('clients/*') ? 'class=active' : '') }}}>
        <a href="{{ route('clients.index') }}">
            <i class="entypo-window"></i><span>Clients</span>
        </a>
    </li>
    @endif
    <li {{{ (Request::is('projects*') ? 'class=active' : '') }}}>
        <a href="{{ route('projects.index') }}">
            <i class="entypo-archive"></i><span>Projects</span>
        </a>
    </li>
    <li {{{ (Request::is('cases*') ? 'class=active' : '') }}}>
        <a href="{{ route('cases.index') }}">
            <i class="entypo-folder"></i><span>Cases</span>
        </a>
    </li>

    @if (Auth::user()->client->enable_wiki)
    <li {{{ (Request::is('pages/wiki*') ? 'class=active' : '') }}}>
        <a href="{{ route('pages.index', 'wiki') }}">
            <i class="entypo-doc-text"></i><span>Wiki</span>
        </a>
    </li>
    @endif

    @if (Auth::user()->client->enable_intranet)
    <li {{{ (Request::is('pages/intranet*') ? 'class=active' : '') }}}>
        <a href="{{ route('pages.index', 'intranet') }}">
            <i class="entypo-window"></i><span>Intranet</span>
        </a>
    </li>
    @endif

    @if (Auth::user()->client->enable_forms)
    <li {{{ (Request::is('pages/forms*') ? 'class=active' : '') }}}>
        <a href="{{ route('pages.index', 'forms') }}">
            <i class="entypo-newspaper"></i><span>Forms</span>
        </a>
    </li>
    @endif

    @if (Auth::user()->isAdmin() || Auth::user()->isClientAdmin())
    <li {{{ (Request::is('statistics*') ? 'class=active' : '') }}}>
        <a href="{{ route('statistics.index') }}">
            <i class="entypo-chart-bar"></i><span>Statistics</span>
        </a>
    </li>
    @endif

    <li {{{ (Request::is('users*') ? 'class=active' : '') }}}>
        <a href="{{ route('users.index') }}">
            <i class="entypo-users"></i><span>Users</span>
        </a>
    </li>


    @if (Auth::user()->isAdminOrClientAdmin() || Auth::user()->isManagerOrRepresentative())
    <li {{{ (Request::is('securitygroups*') ? 'class=active' : '') }}}>
        <a href="{{ route('securitygroups.index') }}">
            <i class="entypo-key"></i><span>Security Groups</span>
        </a>
    </li>
    @endif

    @if (Auth::user()->isAdmin() || Auth::user()->isClientAdmin())
    <li {{{ (Request::is('activity*') ? 'class=active' : '') }}}>
        <a href="{{ route('activity.index') }}">
            <i class="entypo-clock"></i><span>System History</span>
        </a>
    </li>
    @endif

    @if (Auth::user()->isAdmin())
    <li {{{ (Request::is('documentation*') ? 'class=active' : '') }}}>
        <a href="{{ route('documentation.index') }}">
            <i class="entypo-window"></i><span>User Manual</span>
        </a>
    </li>
    @endif
</ul>

app/views/includes/admin/mobileNav.blade.php
<ul>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown">
            <i class="entypo-menu"></i>
        </a>

        <div class="dropdown-menu">
            @include('includes/admin/mainNav')

            <ul>
                <li class="divider"></li>
                <li>
                    <a href="{{ route('documentation.index') }}">
                        <i class="entypo-info-circled"></i>
                        Documentation
                    </a>
                </li>

                {{-- @include('includes/admin/nav/support') --}}
                <li class="divider"></li>
                @include('includes/admin/nav/profile')
            </ul>
        </div>
    </li>
</ul>